version: '3.8'
services:
 playwright-test:
    image: playwright-test
    build:
     context: .
     dockerfile: ./Dockerfile
    command: npm run dockerTest
    volumes:
     - ./playwright-report/:/app/playwright-report
     - ./test-results/:/app/test-results